import { readFileSync, writeFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

const files = [
  'context/personal_knowledge_base.md',
  'context/resume.md',
  'context/part2_technical_deep_dives.md',
  'context/part3_career_philosophy.md',
  'context/part4_personal_context.md',
];

const content = files
  .map((f) => {
    try {
      return readFileSync(join(root, f), 'utf-8');
    } catch {
      console.warn(`Skipping missing file: ${f}`);
      return '';
    }
  })
  .filter(Boolean)
  .join('\n\n---\n\n');

const escaped = content
  .replace(/\\/g, '\\\\')
  .replace(/`/g, '\\`')
  .replace(/\$/g, '\\$');

const output = `// Auto-generated by scripts/bake-context.mjs — do not edit manually
// Re-run: node scripts/bake-context.mjs

export const AHMED_CONTEXT = \`${escaped}\`;
`;

writeFileSync(join(root, 'api', '_context.ts'), output, 'utf-8');
console.log(
  `Baked ${(content.length / 1024).toFixed(1)}KB of context into api/_context.ts`
);
