// Auto-generated by scripts/bake-context.mjs — do not edit manually
// Re-run: node scripts/bake-context.mjs

export const AHMED_CONTEXT = `# Ahmed Felfel - Personal Knowledge Base

_For RAG-powered chat agent - Last updated: November 7, 2025_

---

## Professional Identity

**Current Role:** GTM & Partnerships Engineer at Builder.io  
**Location:** Montréal, QC (Remote)  
**Years of Experience:** 6+ years  
**Specialization:** Bridging product and go-to-market teams through automation, scalable systems, and partner enablement

### Unique Value Proposition

- **Founder-engineer capabilities:** Founded Crate.audio, pivoted from startup to open-source
- Translates technical complexity into business value
- Builds systems that connect ideas to execution
- Focuses on automation that gives time back to teams
- Philosophy: "If software doesn't save time, it's useless" (except games)

### Entrepreneurial Experience

- **Founded Crate.audio** - AI-powered DJ setlist tool
- Initially pursued as startup venture
- Pivoted to open-source route
- Built and maintains Discogs SDK as open-source library
- Demonstrates 0-to-1 product building capability

---

## Career Journey & Timeline

### Builder.io (Apr 2023 - Present)

**Company Growth:** Joined when <30 people, now 100+ employees

#### Partnerships Engineer (Dec 2024 - Present)

**Key Achievements:**

**Builder Academy & Certification Platform**

- Built from scratch serving 500+ users (clients, partners, internal teams)
- **Impact Metrics:**
  - Reduced customer engineer dependency by 40%
  - Freed up team resources to focus on high-value work
  - Commercial clients (least resources) previously consumed most team time
- **Partner Certification Program:**
  - 4 system integrator agencies certified to date
  - Growing pipeline of agencies in certification process
  - Goal: Professional services that can assume technical success for Builder.io customers
- **Transformation:**
  - Moved from Excel spreadsheet onboarding → Complete platform
  - HubSpot integration for account sync
  - Customizable onboarding plans, modules, docs
  - Call booking and recording management
  - Streamlined end-to-end customer journey

**Tech Stack:** Next.js, Convex (real-time backend), Builder.io Publish (CMS), HubSpot sync, Tailwind CSS

**Builder CMS MCP Server**

- Link: https://www.builder.io/c/docs/mcp-builder-server
- Enables prompt-based content model creation
- Automates content management workflows
- Connects Builder.io's two products:
  - **Publish:** CMS side
  - **Fusion:** AI-powered "vibe coding" platform
- Used MCP server to transform Excel workbook (Builder Acceleration Workbook Checklist) into structured onboarding plans

**Sales & Deal Support**

- Average deal size: \$100K
- Notable clients: Uber, Walmart, SumUp
- Built custom plugins to unblock deals:
  - CommerceLayer plugin → Unblocked SumUp deal
  - Various migration tools and demos

#### Customer Engineer (Apr 2023 - Dec 2024)

**Account Management:**

- Managed 60+ strategic accounts solo
- Portfolio included \$300K+ ARR accounts
- Notable clients: JTI, Schneider Electric
- Team scaled: Hired 3 CEs to take over workload during transition to partnerships
- Participated in hiring process and interviewed candidates for Customer Engineer roles

**Unified Demo Contribution**

- Core contributor to https://unified-demo-ecomm.vercel.app/
- GitHub: https://github.com/BuilderIO/unified-demo
- Purpose: Explain Builder.io concepts to customers
- Set bar for best practices in Builder.io implementations
- Used as reference architecture for enterprise customers

**Customer Success Work:**

- Advised on SEO, performance, and scalability
- Led onboarding, integrations, solution architecture
- Built and maintained commerce plugins:
  - **Emporix Plugin:** https://github.com/BuilderIO/builder/tree/main/plugins/emporix
    - NPM: https://www.npmjs.com/package/@builder.io/plugin-emporix
    - Enables Builder.io integration with Emporix e-commerce platform
  - **CommerceLayer Plugin:** https://github.com/BuilderIO/builder/tree/main/plugins/commercelayer
    - NPM: https://www.npmjs.com/package/@builder.io/plugin-commercelayer
    - Built to unblock SumUp deal
    - Enables Builder.io integration with CommerceLayer headless commerce
- Created email templating system for team
- Automated workflows to expand team bandwidth

**Recognition:**

- **Voted MVP (Culture Champ) Q1 2025**
- Award given to employees demonstrating exceptional company values:
  - #work-smart
  - #customer-first
  - #raise-the-bar
  - #be-kind

**Context:** Builder.io was a lean, scrappy startup where "good ideas become projects"

---

### Appnovation (May 2021 - Apr 2023)

**Role:** Full-Stack Developer (Remote/Hybrid)

**Major Project: VMware Interactive Video Communication App**

- Built entire application from scratch
- **Tech Stack:** React, TypeScript, Contentful CMS
- **Features:**
  - Interactive video communication
  - Newsletter system
  - Content feed
  - Complex access control
  - High traffic volume
  - Large user base
- **Architecture:** Used Contentful for dynamic content updates without deployments

**White Label Design System**

- **Purpose:** Enable experimentation and collaboration for product teams
- **Tech Stack:** React component library, Figma API, Storybook
- **Key Features:**
  - Design tokens imported from Figma via Figma API
  - Tokens contextually paired with CSS properties
  - Reusable components across projects
  - Storybook instance for component viewing
  - Robust and adaptable for customization
- **Impact:** Accelerated execution of high-quality digital products for clients

**R&D Work:**

- Developed IPs for Contentful editorial experience
- Used React, TypeScript, Tailwind, and open-source libraries

**Cloud Infrastructure:**

- Provisioned infrastructure using **GCP Terraform**
- Managed VMs, GKE clusters, database instances
- Declarative infrastructure as code

**Certification:**

- **GCP Associate Engineer** (Google Cloud Platform)

**Other Work:**

- Enterprise apps with React/TypeScript & CMS integrations
- Dashboards and plugins
- Delivered scalable client solutions with design & QA teams

---

### Jesta I.S. (Apr 2019 - Apr 2021)

**Role:** Web Developer (Montreal, QC)

**Major Project: POS Back Office System**

- Built entire back office system for point-of-sale
- **Clients:** Puma, Harry Rosen (high-end retail)
- **Tech Stack:** AngularJS
- **Scope:** Full SDLC management
- Collaborated with product/UX teams to meet business needs

---

## Technical Expertise

### Frontend

- **Frameworks:** React, Next.js, TypeScript, AngularJS
- **Styling:** Tailwind CSS
- **Desktop:** Electron
- **Design Systems:** Figma API integration, design tokens, Storybook
- **UI/UX:** Adobe XD, design pattern development

### Backend & Cloud

- **Runtime:** Node.js
- **Architecture:** Serverless, Microservices
- **Cloud:** GCP (Google Cloud Platform)
  - **Certified:** GCP Associate Engineer
  - **IaC:** Terraform (VMs, GKE clusters, databases)
- **APIs:** REST, GraphQL
- **Real-time:** Convex (real-time backend with built-in reactivity)
- **Databases:** SQL, Oracle PL/SQL, MongoDB
- **Containerization:** Docker

### AI & Automation

- **MCP (Model Context Protocol):** Built Builder CMS MCP Server
- **LLM/Agent Integrations:** AI-powered workflows
- **Workflow Automation:** Focus on eliminating repetitive tasks
- **Philosophy:** Automate 90% of routine work, empower humans for 10% exceptions

### CMS & Tooling

- **Builder.io:** Deep expertise in SDKs, Publish (CMS), Fusion (AI coding)
- **Contentful:** Enterprise CMS integrations
- **Custom Integrations:** Plugin development, migration tools

### Cross-Functional Skills

- Sales engineering
- Partner enablement
- Customer migrations
- GTM automation
- Solution architecture
- Technical hiring and candidate interviewing

---

## Side Projects & Entrepreneurial Ventures

### Crate.audio (https://crate.audio) — Founder & Engineer

**Description:** AI-powered DJ setlist tool leveraging Discogs/vinyl metadata

**Entrepreneurial Journey:**

- **Founded as startup:** Initially pursued as commercial venture
- **Pivoted to open-source:** Shifted strategy to open-source route
- **Demonstrates founder-engineer capabilities:** 0-to-1 product building

**Tech Details:**

- Blends music, data, and design
- Uses Discogs API for vinyl metadata
- AI recommendation engine for setlist creation
- Target users: DJs looking to optimize setlist creation

### Discogs SDK (https://github.com/Crate-AI/discogs-sdk)

**Description:** TypeScript SDK for Discogs OAuth 1.0a authentication and API access

**Open Source Details:**

- **NPM Package:** \`@crate.ai/discogs-sdk\`
- **GitHub:** https://github.com/Crate-AI/discogs-sdk
- **Contributors:** 2 (Ahmed Felfel + Govind Mohan)
- **Language:** TypeScript 100%

**Core Features:**

1. **OAuth 1.0a Authentication Flow**
   - Complete OAuth implementation
   - Authorization URL generation
   - Callback handling with verifier
   - Token management
   - Automated authentication with local server (for development)
2. **API Endpoints:**
   - User identity retrieval
   - Collection management
   - Search functionality (releases, artists, labels)
   - Higher API rate limits (authenticated vs. unauthenticated)

3. **Storage Service:**
   - Token persistence
   - Configurable storage path
   - Automatic token management

**Technical Architecture:**

- **Language:** TypeScript 100%
- **Authentication:** OAuth 1.0a protocol
- **API Design:** Promise-based async/await interface
- **Storage:** JSON file-based token storage
- **Development:** Built-in local server for OAuth callback (port 4567)
- **Configuration:** Consumer key/secret, callback URL, user agent

**Example Usage:**

\`\`\`typescript
import { DiscogsSDK, StorageService } from '@crate.ai/discogs-sdk';

const sdk = new DiscogsSDK({
  DiscogsConsumerKey: 'YOUR_KEY',
  DiscogsConsumerSecret: 'YOUR_SECRET',
  callbackUrl: 'http://localhost:4567/callback',
  userAgent: 'MyApp/1.0',
});

// Automated authentication with local server
await sdk.auth.authenticate();

// Get user identity
const identity = await sdk.auth.getUserIdentity();

// Search for music
const results = await sdk.search.getSearchResults({
  query: 'Dark Side of the Moon',
  type: 'release',
});

// Get user's collection
const collection = await sdk.collection.getCollection({
  username: identity.username,
  page: 1,
  perPage: 50,
});
\`\`\`

**Why Built:**

- Needed for Crate.audio development
- No existing TypeScript SDK with OAuth 1.0a support
- Existing solutions lacked proper authentication flow
- Open-sourced to help other developers building music/vinyl applications
- Demonstrates ability to build developer tools and SDKs

**Technical Challenges Solved:**

- OAuth 1.0a implementation (complex signature generation)
- Token persistence and management
- Automated callback handling for development
- Type-safe API interface
- Error handling and timeout management (5-minute auth timeout)

---

## Philosophy & Approach

### On Building Software

- "If software doesn't save time, it's useless" (except games)
- Social media is "a bottomless time pit masquerading as connection"
- Build what you need, then recognize universal patterns
- Ship fast: MVP in weeks, not months
- Use tools that don't fight you (boring tech stack = proven tech stack)

### On Architecture

- Good architecture scales through simplicity, not complexity
- Real-time should be default, not an afterthought
- Content should live outside code (enables non-technical updates)
- Decouple systems with bridge tables for flexibility
- Source of truth matters: sync FROM, never TO

### On Automation

- Find repetitive patterns and codify them
- Automate 90% of routine cases
- Empower humans for 10% exceptions (edge cases, special situations)
- Build audit trails for transparency
- Trust emerges from transparency

### On Velocity

- "Speed kills" (the kind that kills projects before they see daylight)
- In startups, you have a small window that's closing
- Build fast or don't build at all
- Build in the margins: early mornings, late nights
- Know what to skip

### Career Transition Philosophy

- Moved from pure development → GTM/partnerships
- Focus shifted from writing code → building systems that enable others
- Bridge between technical and business teams
- Translate complexity into value
- **Founder-engineer mindset:** Comfortable with 0-to-1 product building
- **Entrepreneurial experience:** Founded Crate.audio, pivoted strategy
- **Open-source contributor:** Built and maintains Discogs SDK

---

## Writing & Thought Leadership

### Topics of Interest

- AI systems and agent architectures
- Productivity and career growth
- Transition from hands-on work to team leadership
- Moving from IC (individual contributor) to partnership roles
- Building systems that scale

### Published Content

- **Academy Case Study:** Comprehensive breakdown of building Builder Academy
- **MCP Ecosystem Guide:** Practical guide to Model Context Protocol
- **Career Transition Reflections:** From IC to partnership-focused roles

### Content Philosophy

- Document what you learn through guides and case studies
- Share authentic experiences over polished advice
- Focus on real problems and how you solved them
- Include technical details AND business impact

---

## Personal Background

### Education

- **Bachelor in Computer Science**
  - College LaSalle, Montreal, QC
  - Sept 2016 – Apr 2019
- **Applied Science** (1 year)
  - University of Montreal
  - Sept 2015 – June 2016

### Languages

- **Native Fluency:** English, French, Arabic
- **Conversational:** Spanish
- Multilingual professional (4 languages)

### Location & Work Style

- Based in Montréal, QC
- Prefers remote work
- "Montréal-based, building globally"

### Interests & Hobbies

**DJing:**

- Active DJ
- Created Crate.audio to solve own problem (setlist creation)
- Maintains Discogs SDK for music/vinyl data access

**Skiing:**

- Regular skier
- (Details to be collected in future interviews)

**Travel:**

- Passionate about travel
- (Favorite destinations and philosophy to be collected)

**Sports:**

- Tennis
- Biking

### Personal Philosophy

- Curiosity-driven: "That same curiosity led me to create crate.audio"
- Builds side projects that "make life a bit smoother"
- Blends technical skills with creative pursuits (music, design)

---

## Network & Presence

### Links

- **Email:** ahmed.felfel@gmail.com
- **Phone:** +1 (514) 506-7010
- **LinkedIn:** (URL to be added)
- **GitHub:** (URL to be added)
- **Personal Site:** (This site)
- **Crate.audio:** https://crate.audio
- **Builder Academy:** https://academy.builder.io
- **Builder CMS MCP Server:** https://www.builder.io/c/docs/mcp-builder-server
- **Discogs SDK:** https://github.com/Crate-AI/discogs-sdk
- **Unified Demo:** https://unified-demo-ecomm.vercel.app/

---

## Key Stories & Anecdotes

### The Academy Origin Story

**Problem:** Repeating same onboarding flow dozens of times, manual spreadsheet tracking

**Insight:** "When you find yourself repeating the same onboarding flow dozens of times, you start seeing patterns. And patterns mean opportunity."

**The Pivot Moment:** During a customer call discussing onboarding frustrations, realized existing learning platform architecture already solved the problem - just needed to connect pieces differently

**Building in the Dark:**

- Built in margins (early mornings, late nights)
- Bet on velocity over perfection
- Used Builder Figma plugin before Fusion launched
- MVP had three parts: access control, content management, progress tracking

**The Realization:** "Onboarding is just learning with gates. Same patterns. Same architecture. Different problem."

### The Unified Demo Impact

- Set standard for how Builder.io should be implemented
- Became reference architecture for enterprise sales
- Helped explain complex concepts to customers
- Established best practices across the company

### The Startup Growth Journey

- Joined Builder.io when <30 people
- Witnessed growth to 100+ employees
- Transitioned from doing everything to building systems that enable others
- Required hiring 3 people to replace individual contributor work

---

## Quantifiable Achievements Summary

### Impact Metrics

- **500+ users** on Builder Academy platform
- **40% reduction** in customer engineer dependency
- **60+ strategic accounts** managed solo
- **\$300K+ ARR** portfolio accounts
- **\$100K average** deal size
- **4 agencies certified**, more in pipeline
- **3 CEs hired** to replace IC workload
- **Company growth:** <30 → 100+ employees during tenure

### Recognition & Awards

- **MVP (Culture Champ) Q1 2025** - Voted by peers for exceptional demonstration of company values:
  - #work-smart: Efficient, high-impact work
  - #customer-first: Prioritizing customer success
  - #raise-the-bar: Setting high standards
  - #be-kind: Collaborative and supportive team member

### Technical Contributions

- Built Builder Academy (full platform)
- Built Builder CMS MCP Server
- Core contributor to Unified Demo
- Built VMware interactive video communication app (Appnovation)
- Built White Label Design System with Figma API integration (Appnovation)
- Built POS back office system (Jesta I.S.)
- Built and maintains commerce plugins:
  - **Emporix Plugin** (https://www.npmjs.com/package/@builder.io/plugin-emporix)
  - **CommerceLayer Plugin** (https://www.npmjs.com/package/@builder.io/plugin-commercelayer)
- Built email templating system
- Maintains Discogs SDK
- Built Crate.audio

---

## Technical Deep Dives (Completed)

### MCP Architecture Philosophy

**Core Philosophy:** Optimize for positive first interaction

- Design MCP servers to not fail
- Minimize user frustration through extensive guardrails
- Interpret user intent and call the right tools automatically
- **Bad MCP Server:** Requires deep knowledge of tools
- **Good MCP Server:** Interprets intent and calls right tools

**Builder CMS MCP Server:**

- 1,750 lines of TypeScript
- 15 tools for content, models, assets, templates
- Smart semantic search (e.g., "video" → mp4, mov, avi, webm, etc.)
- Context-aware tool calling
- Extensive validation and error handling
- User experience optimizations (image previews, clickable URLs, formatted sizes)

### LLM/Agent Integrations

**1. Crate.audio AI Chatbot**

- RAG + DAG for mood-based playlist curation
- BPM + Genre → Mood mapping
- Curates playlists from existing vinyl collection

**2. AI GTM Automation Platform**

- Internal Builder.io platform
- Automates SDR/XDR qualification, research, handoff
- Tech: Convex + React + Vite + HubSpot + Slack
- 6-field qualification framework
- Tracks SDR→AE handoff metrics

### Workflow Automation Approach

**Identifying Opportunities:**

- Pattern recognition in repetitive tasks
- Manual tracking that could be automated
- Bottlenecks in team capacity
- Measure impact potential

**Preferred Tools:**

- Convex (real-time backend)
- Next.js + TypeScript
- MCP for AI integration
- HubSpot for CRM automation

**90/10 Rule:**

- Automate 90% routine work
- Empower humans for 10% exceptions
- Always include audit trails

### Builder.io Implementation Challenges

**Top 5:**

1. Performance optimization (solved with Unified Demo)
2. SEO implementation (SSR/SSG strategies)
3. Integration complexity (custom plugins)
4. Content model design (MCP Server for management)
5. Onboarding (Builder Academy reduced CE dependency 40%)

### High-Traffic Architecture

- SSR/SSG for performance
- CDN leverage
- Image optimization
- Code splitting
- Proper caching strategies
- Unified Demo as reference

### Custom Plugins Built

- Emporix (e-commerce integration)
- CommerceLayer (unblocked SumUp deal)
- Email templating system
- Migration tools

### Crate.audio Details Needed

- Full tech stack breakdown
- How AI recommendation engine works
- Discogs SDK features and user base
- Target user personas
- Problem being solved in detail

### Career Philosophy Details Needed

- What makes you different from other full-stack engineers/solutions architects
- Why the shift from development to GTM/partnerships
- Your "superpower"
- Career narrative thread connecting roles
- 2-3 year vision
- Types of problems that excite you most

### Personal Context Needed

- Origin story: How you got into tech
- Education background
- Why Montreal / remote work preference
- DJing: Genres, notable gigs, mixes
- Skiing: Favorite mountains, locations
- Travel: Favorite destinations, philosophy
- Tennis/Biking: Casual vs competitive
- Current learning focus (AI systems/agent architectures)
- Other side projects
- Blogs/newsletters/people you follow

### Professional Network Details Needed

- Writing topics and content plans
- Talks, podcasts, content created
- Take on AI in GTM/sales engineering
- Open-source contributions
- Communities you're active in

### Practical Details Needed

- Job search status (active/passive/not looking)
- Target companies/roles
- Remote-only or open to relocation
- Compensation expectations
- Actual LinkedIn/GitHub URLs
- Portfolio pieces or case studies
- Personal website or blog

---

## Interview Questions for Next Sessions

### Part 2: Technical Deep Dives

1. Describe your MCP architecture philosophy
2. What LLM/agent integrations have you built beyond MCP?
3. What's your approach to workflow automation?
4. Most common Builder.io implementation challenges?
5. Recommended architecture for high-traffic Builder.io sites?
6. Custom plugins/SDKs you've built?
7. Crate.audio full tech stack and AI engine details
8. Discogs SDK features and user base

### Part 3: Career Philosophy & Positioning

1. What makes you different from other engineers?
2. Why shift from development to GTM/partnerships?
3. What's your superpower?
4. Career narrative thread connecting roles
5. 2-3 year vision
6. Types of problems that excite you

### Part 4: Personal Context

1. Origin story and education
2. Why Montreal?
3. DJing details (genres, gigs)
4. Skiing locations
5. Travel philosophy
6. Current learning focus details
7. Other side projects
8. Influences you follow

### Part 5: Thought Leadership

1. Writing topics and plans
2. Content you've created
3. Take on AI in GTM/sales
4. Open-source work
5. Communities you're active in

### Part 6: Practical Details

1. Career goals and job search status
2. Target roles/companies
3. LinkedIn/GitHub URLs
4. Portfolio pieces

---

_This knowledge base will be continuously updated as more information is gathered through interviews and conversations._


---

# Ahmed Felfel

**AI & GTM Engineer**

[ahmed.felfel@gmail.com](mailto:ahmed.felfel@gmail.com) | +1 (514) 506-7010 | [LinkedIn](#) | [GitHub](#) | Montreal, QC (Remote)

---

## Profile

Full-stack engineer with 6+ years building AI-powered platforms and GTM automation. Built Builder Academy serving 500+ users with 40% reduction in support needs. Track record unblocking \$100K+ deals and managing \$300K+ ARR portfolios. Trilingual (English, French, Arabic). Specialized in workflow automation, scalable systems, and partner enablement.

---

## Experience

### **Builder.io** _(Remote)_

#### **Partnerships Engineer**

_Dec 2024 – Present_

- Built **Builder Academy** platform serving **500+ users**
- Reduced customer engineer dependency by **40%**
- Streamlined **partner certification program** for system integrators (**4 agencies certified**, pipeline growing)
- Architected **Builder CMS MCP Server** enabling content automation across Publish and Fusion platforms
- Unblocked **\$100K+ enterprise deals** (Uber, Walmart, SumUp) with custom plugins
- Supported sales team and managed full-funnel ownership

#### **Customer Engineer**

_Apr 2023 – Dec 2024_

- Managed **60+ strategic accounts** with **\$300K+ ARR** (JTI, Schneider Electric)
- Advised customers on SEO, performance, and scalability
- Core contributor to **Unified Demo** for best practices
- Built plugins ([Emporix](https://www.npmjs.com/package/@builder.io/plugin-emporix), [CommerceLayer](https://www.npmjs.com/package/@builder.io/plugin-commercelayer)) for e-commerce
- Scaled team from **<30 to 100+ employees**
- **Hired 3 engineers** during transition
- **Voted MVP Q1 2025**

---

### **Appnovation** _(Remote/Hybrid)_

#### **Full-Stack Developer**

_May 2021 – Apr 2023_

- Built **VMware interactive video communication app** (Electron, React, TypeScript, Contentful) with complex access control and high traffic
- Developed **White Label Design System**: React component library with Figma API integration, design tokens, and Storybook
- Provisioned cloud infrastructure using **GCP Terraform** (VMs, GKE clusters, database instances)
- **Certified GCP Associate Engineer**

---

### **Jesta I.S.** _(Montreal, QC)_

#### **Web Developer**

_Apr 2019 – Apr 2021_

- Built **POS back office system** for enterprise retail clients (Puma, Harry Rosen)
- Full SDLC management with AngularJS, Java, Oracle PL/SQL
- Collaborated with product/UX teams on business requirements

---

## Projects

### **[Crate.audio](https://crate.audio)** — _Founder & Engineer_

AI-powered DJ setlist tool leveraging Discogs/vinyl metadata for mood-based playlist curation. Founded as startup, pivoted to open-source.

- Built **[Discogs SDK](https://github.com/Crate-AI/discogs-sdk)**: TypeScript SDK for Discogs OAuth authentication and API access
- Published on NPM: \`@crate.ai/discogs-sdk\`
- Supports authentication flow, collection management, search, and user identity

---

## Technical Skills

**Frontend:** React, Next.js, TypeScript, Tailwind, Electron  
**Backend/Cloud:** Node.js, Serverless, Convex, GCP (Terraform, certified), REST, GraphQL, MongoDB, Docker  
**AI/Automation:** MCP (Model Context Protocol), LLM/agent integrations, workflow automation  
**CMS/Tooling:** Builder.io (Publish, Fusion), Contentful, custom integrations  
**Cross-Functional:** Sales engineering, partner enablement, migrations, GTM automation, technical hiring

---

## Education

**Bachelor in Computer Science**  
_College LaSalle, Montreal, QC_ — Sept 2016 – Apr 2019

---

## Languages

**Native Fluency:** English, French, Arabic  
**Conversational:** Spanish

---

## Awards

**MVP (Culture Champ) Q1 2025** — Builder.io  
Voted by peers for exceptional demonstration of company values


---

# Part 2: Technical Deep Dives - Interview Results

_Date: November 7, 2025_

---

## MCP Architecture Philosophy

### Design Principles

**Core Philosophy: Optimize for Positive First Interaction**

- Design MCP servers to not fail
- Minimize user frustration through extensive guardrails
- Ensure first prompt delivers best result
- Interpret user intent and call the right tools automatically

**Key Differentiators:**

- **Bad MCP Server:** Requires really good knowledge of MCP servers and their tools
- **Good MCP Server:** Interprets what the user wants and calls the right tools automatically

### Builder CMS MCP Server Architecture

**Official Documentation:** https://www.builder.io/c/docs/mcp-builder-server  
**File:** \`McpContentServer.ts\` (1,750 lines)  
**Available For:** Pro plans (Publish and Hybrid Spaces only)

**Core Design Decisions:**

1. **Context-Aware Tool Calling**
   - If users ask for something that needs prior context, automatically run the right tools
   - Gather necessary context before executing main request
   - Chain tool calls intelligently to build complete picture

2. **Extensive Validation & Error Handling**
   - Validate all inputs before processing
   - Sanitize errors to prevent exposing sensitive information
   - Provide helpful error messages with guidance
   - Example: Search text validation with specific feedback

3. **Smart Semantic Search**
   - Expand search terms intelligently
   - Example: "video" → searches for mp4, mov, avi, webm, mkv, flv, m4v, wmv
   - Example: "image" → searches for jpg, jpeg, png, gif, webp, svg, bmp, tiff, ico
   - Makes search intuitive for non-technical users

4. **User Experience Optimizations**
   - Display instructions included in responses
   - Image previews inline for visual assets
   - Clickable URLs
   - Formatted file sizes and dimensions
   - Human-friendly error messages

### MCP Server Tools (12 Total)

**Content Operations:**

1. **\`get_builder_content\`** - Get content with specific query filters
   - Use when you have precise criteria or know exactly what you're looking for
   - Example: "get the homepage content from the 'page' model where the name equals 'home'"

2. **\`browse_model_content\`** - Browse all content in a model without filters
   - Use for getting an overview of available content
   - Example: "show me all the blog posts in the 'blog-post' model"

3. **\`search_builder_content\`** - Text search across all models
   - Use when you don't know exact model or location but have keywords
   - Set \`returnFullContent=true\` for complete content structure
   - Example: "search for all content containing 'product launch' and return the full content structure"

4. **\`create_builder_content\`** - Create new content entries
   - Works across any available model
   - Automatic URL generation for page-type models
   - Handles field validation according to model schema
   - Example: "Create a new blog post with title 'Getting Started' and content about onboarding"

5. **\`update_builder_content\`** - Update existing content
   - Preserves data integrity and relationships
   - Returns direct links to Builder.io editor and live page URLs
   - Example: "Update the homepage content to change the hero title to 'Welcome to Our Store'"

**Model Operations:** 6. **\`list_builder_models\`** - List all available models

- Complete inventory of content models in your space
- Understand content architecture
- Example: "what content models are available in this Builder Space?"

7. **\`get_model_schema\`** - Get detailed schema definition
   - Reveals complete field structure, data types, validation rules
   - Use before creating new entries or querying content
   - Example: "show me the schema for the 'product' model"

8. **\`create_builder_model\`** - Create new content models
   - Define field types, validation rules, model properties
   - Types: data, component, page, section, or symbol
   - Example: "Create a new 'testimonial' model with fields for customer name, quote, company, and rating"

9. **\`update_builder_model\`** - Modify existing models
   - Add new fields, modify properties, update validation rules
   - Preserves existing content and relationships
   - Example: "Update the 'product' model to add a new field for product dimensions and make the description field required"

**Asset & Structure:** 10. **\`search_assets\`** - Search digital assets (images, videos, documents) - Automatically displays image previews inline - Makes all asset URLs clickable - Supports filename patterns, asset types, metadata - Example: "Find all product images containing 'hero' in the filename"

11. **\`get_pages_hierarchy\`** - Get complete site structure
    - Shows parent-child relationships between pages
    - Navigation structures and site architecture
    - Example: "show me the complete site structure and page hierarchy"

12. **\`get_templates\`** - Get available templates (user + Builder official)

### Technical Implementation Details

**Protocol:** MCP (Model Context Protocol) v2024-11-05  
**Transport:** Streamable HTTP (SSE-compatible)  
**Authentication:** Bearer token with Private API Key  
**Endpoint:** \`https://cdn.builder.io/api/v1/mcp/builder-content\`  
**Session Management:** Secure session IDs with resumable connections

**Connection Configuration (JSON):**

\`\`\`json
{
  "mcpServers": {
    "builder-cms": {
      "url": "https://cdn.builder.io/api/v1/mcp/builder-content",
      "transport": "http",
      "headers": {
        "Authorization": "Bearer YOUR_PRIVATE_API_KEY"
      }
    }
  }
}
\`\`\`

**Compatible Clients:**

- AI coding assistants
- IDE extensions (VS Code, Cursor, etc.)
- LLM-based tools
- Any MCP-compatible client

**Verification Prompts:**

- "What content models are available in this Builder Space?"
- "Show me all Pages in my Builder Space."
- "Search for content containing 'homepage'."

**Key Features:**

- JSON-RPC 2.0 protocol
- Health check endpoint
- Session initialization and termination
- Tool listing and execution
- Resource listing and access
- Origin validation
- Error sanitization for security

**Performance Optimizations:**

- Query limits (100 for content, 50 for assets)
- Asset processing limits (100 max)
- Pagination support with offset
- Field selection to reduce payload size
- Smart caching strategies

**Integration Points:**

- Firebase Firestore for models/templates
- MongoDB for content queries
- Builder.io Content API
- Builder.io Assets API
- Builder.io Pages Hierarchy API
- Mitosis for JSX conversion

---

## LLM/Agent Integrations

### 1. Crate.audio AI Chatbot

**Purpose:** Curate playlists based on mood using your existing vinyl collection

**Architecture:**

- **RAG (Retrieval-Augmented Generation):** Fetch relevant vinyl metadata from Discogs
- **DAG (Directed Acyclic Graph):** Process BPM and genre data to determine mood
- **Mood Mapping:** BPM + Genre → Mood → Playlist curation

**Tech Stack:**

- Next.js + TypeScript frontend
- Discogs SDK for OAuth and API access
- YouTube audio extraction (yt-dlp)
- AI analysis for BPM and mood detection

**Key Features:**

- Sign in with Discogs OAuth
- Access user's vinyl collection
- Extract audio from YouTube for analysis
- AI-powered mood detection
- Curate playlists from existing collection

**User Flow:**

1. User signs in with Discogs
2. System fetches vinyl collection metadata
3. User specifies desired mood
4. AI analyzes BPM, genre, and other metadata
5. System curates playlist matching mood from user's collection

### 2. AI GTM Automation Platform

**Repository:** BuilderIO/ai-gtm (private)
**Purpose:** Builder's internal AI-driven go-to-market automation platform

**Problem Solved:**
Automate SDR/XDR qualification, research, and handoff workflows so GTM teams can process leads faster and more consistently.

**Key Workflows:**

1. **Lead Kickoff (Automated)**
   - Trigger from HubSpot when lead arrives
   - Fetch context about lead
   - Summarize persona and intent
   - Generate draft outreach

2. **Qualification (Standardized)**
   - 6-field qualification framework
   - Persona identification
   - Trigger analysis
   - Use case determination
   - Next step recommendation
   - Write back to GTM systems

3. **AE Handoff (Instrumented)**
   - Track SDR→AE handoff metrics
   - Measure lag time
   - Track conversion rates
   - Measure impact

**Architecture:**

**Backend & State:**

- **Convex:** Backend functions and database
- Real-time state management
- Orchestration of workflows

**Frontend:**

- **React + Vite:** Prioritized tasks, summaries, recommended actions
- **Tailwind CSS:** Rapid internal UI iteration

**Integrations:**

- **HubSpot:** Lead triggers, data sync
- **Slack:** Notifications and updates
- **Sigma/Notion:** Metrics dashboards (planned)
- Internal Builder.io systems

**Roadmap:**

**Phase 1 (Current):**

- Automate lead kickoff
- Qualification automation
- Outreach drafting
- AE handoff instrumentation

**Phase 2 (Planned):**

- Feedback loop implementation
- Metrics dashboards (Sigma, Notion)

**Phase 3 (Future):**

- Expand upstream: Marketing→SDR automation
- AE-facing pipeline intelligence

**Documentation:**

- Internal Notion GTM AI Systems Hub: https://www.notion.so/builderio/28a3d7274be58014b5cbd31412d932f6
- Repo docs: roadmap, API & schema references, qualification model
- Master prompt: \`scope/docs/masterprompt.md\`
- Scope doc: \`scope/scope.md\`

---

## Workflow Automation Approach

### Identifying Automation Opportunities

**Philosophy:** "If software doesn't save time, it's useless"

**Pattern Recognition:**

1. Identify repetitive tasks (e.g., same onboarding flow dozens of times)
2. Look for manual tracking (e.g., spreadsheets for customer progress)
3. Find bottlenecks (e.g., team capacity constraints)
4. Measure impact potential (e.g., 40% reduction in CE dependency)

**Examples:**

- **Builder Academy:** Repetitive onboarding → Automated learning platform
- **AI GTM:** Manual lead qualification → Automated SDR workflows
- **MCP Server:** Manual content management → Prompt-based automation

### Preferred Tools/Frameworks

**Backend:**

- **Convex:** Real-time backend, automatic reactivity, no cache invalidation
- **Node.js:** Serverless functions
- **Firebase Functions:** Scalable cloud functions

**Frontend:**

- **React/Next.js:** Component-based UI
- **TypeScript:** Type safety
- **Tailwind CSS:** Rapid styling

**Automation:**

- **MCP (Model Context Protocol):** AI-powered tool integration
- **LLM Integrations:** OpenAI, Claude for intelligent automation
- **Workflow Orchestration:** Convex for state management

**Integration:**

- **HubSpot:** CRM automation
- **Slack:** Notifications
- **Builder.io APIs:** Content management

### Balancing Automation vs. Human Control

**90/10 Rule:**

- **Automate 90%:** Routine cases, repetitive tasks, standard workflows
- **Empower humans for 10%:** Exceptions, edge cases, special situations

**Implementation:**

- **Automation handles:** Standard lead qualification, content creation, progress tracking
- **Humans handle:** Complex deals, special customer needs, strategic decisions
- **Audit trails:** Log all overrides for transparency
- **Manual overrides:** Allow humans to intervene when needed

**Example (Builder Academy):**

- Automation: Progress tracking, session unlocking, checkpoint completion
- Human control: Manual overrides for VIP customers, threshold adjustments, special cases
- Transparency: Every override logged with who, when, why

---

## Builder.io Expertise

### Common Implementation Challenges

**Top 5 Challenges:**

1. **Performance Optimization**
   - Challenge: Slow page loads, poor Core Web Vitals
   - Solution: Unified Demo as reference architecture
   - Best practices: SSR, image optimization, code splitting

2. **SEO Implementation**
   - Challenge: Dynamic content not indexed properly
   - Solution: SSR/SSG strategies, proper meta tags
   - Advised enterprise customers on SEO best practices

3. **Integration Complexity**
   - Challenge: Connecting Builder.io with existing tech stack
   - Solution: Custom plugins (Emporix, CommerceLayer)
   - Built integrations for e-commerce platforms

4. **Content Model Design**
   - Challenge: Structuring content for flexibility and scalability
   - Solution: MCP Server to programmatically manage models
   - Guidance on field types, validation, relationships

5. **Onboarding & Learning Curve**
   - Challenge: Customers struggling to get started
   - Solution: Builder Academy with self-service learning
   - Reduced CE dependency by 40%

### High-Traffic Architecture Recommendations

**Performance Strategies:**

- **SSR/SSG:** Server-side rendering or static generation
- **CDN:** Leverage Builder.io's CDN for assets
- **Image Optimization:** Automatic image optimization via Builder.io
- **Code Splitting:** Load only what's needed
- **Caching:** Implement proper caching strategies

**Scalability:**

- **Unified Demo:** Reference architecture for high-traffic sites
- **Best Practices:** Documented in Unified Demo repository
- **Enterprise Guidance:** Advised \$300K+ ARR accounts on architecture

### Custom Plugins/SDKs Built

**Commerce Plugins:**

1. **Emporix Plugin**
   - NPM: \`@builder.io/plugin-emporix\`
   - GitHub: https://github.com/BuilderIO/builder/tree/main/plugins/emporix
   - Purpose: Builder.io integration with Emporix e-commerce platform
   - Features: Product catalog, cart integration, checkout

2. **CommerceLayer Plugin**
   - NPM: \`@builder.io/plugin-commercelayer\`
   - GitHub: https://github.com/BuilderIO/builder/tree/main/plugins/commercelayer
   - Purpose: Builder.io integration with CommerceLayer headless commerce
   - Business Impact: Built to unblock SumUp deal (\$100K+)
   - Features: Product management, order processing, inventory

**Other Contributions:**

- Email templating system for internal team
- Migration tools for customer onboarding
- Custom demos for enterprise sales

---

## Crate.audio Deep Dive

### Full Tech Stack

**Frontend:**

- **Framework:** Next.js 14 (App Router)
- **Language:** TypeScript
- **Styling:** Tailwind CSS
- **Font:** Inter (custom)
- **UI Components:** Custom React components

**Backend/API:**

- **Runtime:** Node.js
- **API Routes:** Next.js API routes
- **Authentication:** Discogs OAuth 1.0a
- **Audio Extraction:** yt-dlp (Python tool)

**Integrations:**

- **Discogs SDK:** Custom-built TypeScript SDK for OAuth and API access
- **YouTube:** Audio extraction via yt-dlp
- **Storage:** Local JSON file for OAuth tokens (StorageService)

**Development:**

- **Package Manager:** pnpm
- **Dev Server:** \`pnpm dev\` on localhost:3000
- **Dependencies:** Discogs SDK, yt-dlp

**Infrastructure:**

- **Hosting:** (To be determined - currently development)
- **Images:** Remote images from i.discogs.com allowed
- **Storage:** Local file system for token storage

### Technology Choices

**Why Next.js:**

- Fast to prototype
- Built-in API routes
- App Router for modern React patterns
- Image optimization out of the box
- Easy deployment

**Why TypeScript:**

- Type safety for API integrations
- Better developer experience
- Catch errors at compile time
- Essential for SDK development

**Why Discogs:**

- Comprehensive vinyl metadata
- Rich music database
- OAuth for secure access
- User's existing collection data

**Why yt-dlp:**

- Reliable YouTube audio extraction
- Open-source and well-maintained
- Supports multiple formats
- Required for audio analysis

### What Would Change If Rebuilding Today

**Potential Improvements:**

1. **Use Builder Fusion:** Now available, would use for rapid prototyping
2. **Database:** Move from local JSON to proper database (Convex or Supabase)
3. **Authentication:** More robust token management
4. **Deployment:** Containerize with Docker for easier deployment
5. **Audio Processing:** Cloud-based audio extraction instead of local yt-dlp

### AI Recommendation Engine

**How It Works:**

1. **Data Collection:**
   - Fetch user's vinyl collection from Discogs
   - Extract metadata: BPM, genre, year, artist, label
   - Optionally extract audio from YouTube for analysis

2. **Mood Mapping (DAG Approach):**
   - **BPM Analysis:** Slow (60-90) → Chill, Medium (90-120) → Moderate, Fast (120+) → Energetic
   - **Genre Mapping:** Genre → Mood associations (e.g., Jazz → Relaxed, Techno → Energetic)
   - **Combined Analysis:** BPM + Genre → Refined mood classification

3. **Playlist Curation:**
   - User specifies desired mood
   - AI filters collection based on mood parameters
   - Ranks results by relevance
   - Returns curated playlist from user's existing collection

**Data Sources:**

- **Discogs API:** Vinyl metadata (genre, year, artist, label)
- **User Collection:** Personal vinyl library
- **Audio Analysis:** BPM detection from YouTube audio (optional)
- **Genre Database:** Pre-built genre-to-mood mappings

**Algorithms/Models:**

- **BPM Detection:** Audio analysis algorithms (if using YouTube audio)
- **Genre Classification:** Rule-based mapping (genre → mood)
- **Ranking Algorithm:** Weighted scoring based on BPM + genre match
- **RAG Pattern:** Retrieve relevant vinyl → Augment with metadata → Generate playlist

### Discogs SDK Details

**NPM Package:** \`@crate.ai/discogs-sdk\`
**GitHub:** https://github.com/Crate-AI/discogs-sdk

**Usage Stats:**

- **Stars:** 2
- **Forks:** 1
- **Commits:** 81
- **Contributors:** 2 (Ahmed Felfel + Govind Mohan)
- **Downloads:** (To be tracked via NPM)

**Who Uses It:**

- Crate.audio (primary use case)
- Developers building music/vinyl applications
- Anyone needing TypeScript SDK for Discogs OAuth

**Roadmap:**

1. **Current:** OAuth 1.0a authentication, collection management, search, user identity
2. **Planned:**
   - Release management
   - Marketplace integration
   - Wantlist management
   - Community features
   - Better documentation
   - Example projects
   - NPM download tracking

### Problem & Users

**Specific Problem Solved:**
DJs and vinyl collectors need an easy way to curate playlists based on mood from their existing vinyl collection, but:

- Manual curation is time-consuming
- Hard to remember what vinyl you own
- Difficult to match vinyl to specific moods
- No existing tools combine Discogs + AI + mood-based curation

**Target User:**

- **Primary:** DJs who own vinyl and need to plan sets
- **Secondary:** Vinyl collectors who want to rediscover their collection
- **Tertiary:** Music enthusiasts exploring mood-based listening

**User Journey:**

1. **Discovery:** Land on waitlist page
2. **Sign Up:** Join waitlist
3. **Authentication:** Sign in with Discogs OAuth
4. **Collection Sync:** System fetches vinyl collection
5. **Mood Selection:** User specifies desired mood (e.g., "chill evening vibes")
6. **Playlist Generation:** AI curates playlist from collection
7. **Playback:** (Future) Integration with streaming or local playback

**Current State:**

- Waitlist/landing page live
- Discogs OAuth implemented
- YouTube audio extraction working
- AI curation in development
- Full product launch pending

---

## Key Technical Insights

### MCP Server Design Philosophy

**Core Principle:** Optimize for positive first interaction

- Interpret user intent automatically
- Call right tools without user knowing MCP internals
- Extensive validation and helpful error messages
- Smart semantic search (e.g., "video" → all video extensions)

### Automation Philosophy

**90/10 Rule:**

- Automate 90% of routine work
- Empower humans for 10% exceptions
- Always include audit trails
- Trust emerges from transparency

### Real-Time is Default

**Convex Philosophy:**

- No polling required
- No cache invalidation needed
- Data changes → UI updates automatically
- Build differently when real-time is default

### Content Should Live Outside Code

**Separation of Concerns:**

- Builder CMS for content
- Code for logic
- Marketing updates content without engineering
- Reduces maintenance, enables velocity

---

## Technical Contributions Summary

**MCP Servers:**

- Builder CMS MCP Server (1,750 lines, 15 tools)
- Optimized for UX, extensive guardrails
- Smart semantic search, context-aware tool calling

**AI/LLM Integrations:**

- Crate.audio AI chatbot (RAG + DAG for mood-based curation)
- AI GTM automation platform (SDR workflow automation)
- Builder Academy (AI-powered learning platform)

**SDKs & Libraries:**

- Discogs SDK (TypeScript, OAuth 1.0a, NPM published)
- Builder.io plugins (Emporix, CommerceLayer)

**Platforms Built:**

- Builder Academy (500+ users, 40% CE reduction)
- AI GTM (internal automation platform)
- Crate.audio (mood-based playlist curation)

---

_Part 2 Technical Deep Dives completed. Ready for Part 3: Career Philosophy & Positioning._


---

# Part 3: Career Philosophy & Positioning - Interview Results

_Date: November 7, 2025_

---

## 1. Unique Value Proposition

### What Makes You Different

**Well-Rounded Problem Solver:**

- Understand pain points deeply
- Build complete solutions end-to-end
- No dependency on designers or PMs

**Autonomous Execution:**

- **Key Differentiator:** Complete autonomy from concept to launch
- Don't need a designer: Keen eye for UX and slick design
- Don't need a PM: Can identify problems, prioritize, and execute
- Self-sufficient across the full product development lifecycle

**Blazing Fast Prototyping:**

- Rapid iteration from idea to working prototype
- Speed without sacrificing quality
- Quick validation of concepts

**High Performance in High-Growth Environment:**

- Work at a very talented, high-growth startup (Builder.io)
- Recognized as one of their best high performers
- Performance driven by hard work, not luck
- Proven ability to deliver in fast-paced, demanding environments

### Unique Combination of Skills

**Technical + Design + Product:**

- **Technical:** Full-stack development, AI/LLM integrations, infrastructure
- **Design:** UX intuition, visual design sense, user-first thinking
- **Product:** Problem identification, prioritization, solution architecture

**Builder + Operator:**

- Build platforms (Academy, MCP Server, Crate.audio)
- Operate and scale them (500+ users, enterprise customers)
- Understand both creation and maintenance

**Customer-Facing + Engineering:**

- Customer Engineer background: understand customer pain deeply
- Partnerships Engineer: understand GTM and business needs
- Translate between technical and business stakeholders

**Individual Contributor + Team Scaler:**

- Can execute autonomously at high velocity
- Also scaled teams (helped hire 3 CEs, team grew <30 to 100+)
- Mentor and enable others while shipping

### "Superpower"

**0 → 1 Product Builder with Enterprise Empathy**

- Take ambiguous problems and ship complete solutions
- Understand enterprise needs from CE/partnerships experience
- Build with scale and quality in mind from day one
- Move fast without breaking things
- Design, build, and launch autonomously

**Speed + Quality + Autonomy**

- Prototype faster than most
- Ship production-quality code
- Don't need hand-holding or extensive direction
- Self-directed and self-motivated

---

## 2. Career Transition Story

### Developer → Customer Engineer (Apr 2023)

**What Drove the Transition:**

- Wanted to be more in touch with client pain points
- Broaden skillset beyond pure engineering
- Develop communication skills

**The Engineer Communication Problem:**

- "Engineers tend to hit a wall when talking to non-technical users"
- Recognized this as a career-limiting skill gap
- Wanted to bridge technical and business worlds

**What You Learned:**

- **Hard Skills:**
  - Solution architecture for enterprise customers
  - SEO and performance optimization
  - Integration patterns and best practices
  - Onboarding and migration strategies

- **Soft Skills:**
  - Translating technical concepts for non-technical audiences
  - Understanding customer pain points deeply
  - Managing expectations and building trust
  - Navigating complex enterprise organizations

**How It Compounds:**

- Can now build solutions with deep customer empathy
- Understand what customers actually need vs. what they ask for
- Bridge between engineering and business stakeholders
- Build products that solve real problems, not imagined ones

### Customer Engineer → Partnerships Engineer (Dec 2024)

**What Drove the Transition:**

- "Partnership was a welcome sight"
- Opportunity to work with more technically savvy people
- Develop certification programs
- Cover the entire pipeline from discovery to enablement

**What Partnerships Covers (Full Funnel):**

1. **Marketing:** Evangelize Builder (webinars, content)
2. **Pre-Sales:** Discovery and qualification
3. **Sales:** Technical sales support
4. **Post-Sales:** Implementation and enablement
5. **Customer Success:** Ongoing support and growth

**Role Definition:**

- "Fusion of a sales engineer and a customer engineer"
- More strategic than CE work
- Focus on partners (agencies, SIs) not just direct customers
- Build programs and platforms (Academy, certification)

**What You Learned:**

- **Program Development:**
  - Built Builder Academy for partner certification
  - Developed certification framework
  - Created scalable enablement programs

- **Evangelism:**
  - Joined many webinars to evangelize Builder
  - Public speaking and thought leadership
  - Partner relationship building

- **Full-Funnel Thinking:**
  - Understand entire customer journey
  - Not just implementation, but discovery through success
  - Strategic vs. tactical focus

**How It Compounds:**

- Can now build platforms that scale enablement (not just 1:1 support)
- Understand partner ecosystem and channel strategy
- Think strategically about GTM automation
- Evangelize and build in public

### Overall Compounding Effect

**Three Perspectives = Unique Value:**

1. **Developer Background:**
   - Can build anything autonomously
   - Understand technical constraints and possibilities
   - Fast prototyping and shipping

2. **Customer Engineer Experience:**
   - Deep customer empathy
   - Understand enterprise pain points
   - Know what customers actually need

3. **Partnerships Engineer Experience:**
   - Full-funnel GTM understanding
   - Platform/program thinking (not just features)
   - Evangelism and thought leadership

**Result:**

- Build products that solve real customer problems
- Create scalable solutions (platforms, not point solutions)
- Bridge technical, customer, and business perspectives
- Autonomous execution with strategic thinking

---

## 3. Builder vs. Operator

### Preference: Building or Operating?

**Strongly Prefer Building (Especially with AI):**

- "Software has become super cheap" with AI
- Can build custom platforms faster than adopting/configuring existing tools
- More granular focus on team's specific needs
- Avoid the "purchase operator" problem

**The "Purchase Operator" Problem:**

- Very hard to purchase operators now
- New tools require adoption and setup overhead
- Training and onboarding friction
- Generic tools don't fit specific workflows perfectly

### Philosophy: "Best-in-Class APIs + Custom Glue"

**Preferred Architecture:**

- Use tools that are "really good at something"
- Access their value through APIs
- Build custom platform that orchestrates these services
- Own the integration layer and user experience

**Why This Works:**

- **Speed:** Faster to build custom than configure generic
- **Fit:** Exact match to team needs, not "close enough"
- **Control:** Own the experience and workflow
- **Flexibility:** Easy to swap underlying services via API
- **No Adoption Friction:** Build exactly what team needs

**Examples in Practice:**

- **Builder Academy:** Custom platform, not off-the-shelf LMS
- **AI GTM:** Custom automation, not generic CRM workflows
- **MCP Server:** Custom tools, not generic CMS integrations

### Build vs. Buy/Integrate Decision Framework

**Build Custom When:**

1. **Workflow is unique:** Team needs don't match generic tools
2. **Speed matters:** Can build faster than configure/adopt
3. **Integration is key:** Need to orchestrate multiple services
4. **UX is critical:** Generic tools have poor UX for your use case
5. **AI can accelerate:** With AI, building is now faster than buying

**Integrate via API When:**

- Tool is best-in-class at one thing
- API is robust and well-documented
- Service handles complexity you don't want to own
- Examples: HubSpot for CRM, Discogs for music data, Builder.io for CMS

**Avoid Buying When:**

- Requires "purchase operator" (dedicated person to manage)
- Long setup/adoption time
- Doesn't fit workflow well
- Generic solution to specific problem

### Balancing "Ship Fast" vs. "Build It Right"

**With AI: Both Are Possible**

- AI enables rapid prototyping without sacrificing quality
- Can iterate quickly and refine
- "Build it right" doesn't mean "build it slow" anymore

**Philosophy:**

- Ship fast to validate
- Build with quality from start (not "move fast and break things")
- Iterate based on real usage
- AI makes "fast + right" achievable simultaneously

**Examples:**

- **Builder Academy:** Shipped fast, iterated based on 500+ user feedback
- **MCP Server:** Built with extensive guardrails from day one
- **Crate.audio:** Rapid prototyping to test concept

---

---

## 4. Future Vision (2-3 Years)

### Career Goal: AI Engineer → AI Engineering Leader

**Current State:**

- "I want to become an AI engineer"
- "This is what I'm doing right now at Builder minus the title"
- Title coming soon

**2-3 Year Vision:**

- **Immediate:** Formalize AI Engineer role
- **Mid-term:** Lead an AI engineering team
- **Long-term:** Become a leading voice on building AI products

**Target Role Progression:**

1. **AI Engineer** (current, unofficial)
2. **Senior AI Engineer / Staff AI Engineer**
3. **AI Engineering Team Lead**
4. **Industry Pioneer/Thought Leader**

### Problems You Want to Solve

**Primary Focus: Workflow Automation**

- "Biggest opportunities in automating manual work"
- Build AI products that eliminate repetitive tasks
- Focus on GTM, sales, customer success workflows
- Create platforms that scale human effort

**Specific Problem Areas:**

- GTM automation (like AI GTM platform)
- Developer productivity (like MCP servers)
- Customer enablement (like Builder Academy)
- Workflow orchestration and integration

### Technical Focus: MCP Servers & Guardrails

**Why MCP Servers Are Critical:**

- "Absolutely important for safety purposes"
- Building AI at scale requires guardrails
- Prevent hallucinations
- Ensure reliability and trust

**Philosophy:**

- AI without guardrails is dangerous at scale
- MCP servers provide structure and safety
- Balance speed with reliability
- Make AI trustworthy for enterprise use

### Thought Leadership Goal

**Become Industry Pioneer:**

- Leading voice on building AI products for workflow automation
- Share learnings and best practices publicly
- Evangelize safe, scalable AI development
- Contribute to the field through writing, speaking, building

**What "Leading Voice" Means:**

- Not just building, but teaching others
- Open source contributions
- Conference talks and webinars
- Writing and documentation
- Building in public

### Ideal Company/Team Environment

**Type of Company:**

- High-growth startup or scale-up (like Builder.io)
- AI-first or AI-native company
- Building products that automate workflows
- Strong engineering culture

**Team Characteristics:**

- Talented, high-performing team
- Fast-paced but sustainable
- Values autonomy and ownership
- Encourages experimentation
- Supports thought leadership and building in public

**Work Style:**

- Remote or hybrid
- Async-first communication
- Trust and autonomy
- Focus on impact over hours

**Industry/Domain:**

- Developer tools
- GTM/sales automation
- Workflow automation platforms
- AI infrastructure

---

## 5. AI & Automation Philosophy

### AI: Replacing vs. Augmenting Human Work

**The 90/10 Rule (Revisited):**

- **Automate 90%:** Repetitive, manual work that doesn't require human judgment
- **Augment 10%:** Complex decisions, edge cases, strategic thinking

**Philosophy:**

- AI should eliminate toil, not jobs
- Humans should focus on high-value work
- Automation frees people to do what they're best at
- "Software has become super cheap" means we should automate aggressively

**What AI Should Do:**

- Repetitive data entry and processing
- Standard qualification and research
- Content generation and summarization
- Workflow orchestration
- Pattern recognition and recommendations

**What Humans Should Do:**

- Complex problem-solving
- Strategic decision-making
- Relationship building
- Creative work
- Handling exceptions and edge cases

### Future of GTM/Sales Engineering with AI

**AI Will Transform, Not Replace:**

- SDRs/CEs won't disappear, but role will evolve
- AI handles routine qualification and research
- Humans focus on complex deals and relationships
- Higher leverage per person

**What a CE Looks Like in 3 Years:**

- **Less:** Manual research, repetitive onboarding, standard questions
- **More:** Strategic consulting, complex integrations, relationship building
- **Tools:** AI assistants for research, MCP servers for automation, platforms like AI GTM
- **Skills:** Higher technical bar, better communication, strategic thinking

**Impact on Teams:**

- Smaller teams with higher output
- Each person handles more accounts
- Focus on quality over quantity
- AI handles scale, humans handle complexity

### Biggest AI Opportunities (Next 2-3 Years)

**1. Workflow Automation (Highest Priority)**

- "Biggest opportunities in automating manual work"
- GTM workflows (like AI GTM)
- Customer success workflows
- Internal operations
- Cross-functional orchestration

**2. Developer Productivity**

- MCP servers for safe, scalable AI integration
- Code generation with guardrails
- Automated testing and debugging
- Documentation generation

**3. MCP Servers & Safety Infrastructure**

- "Absolutely important for safety purposes"
- Building AI at scale requires guardrails
- Prevent hallucinations
- Enterprise-grade reliability
- Trust and transparency

**4. Custom Internal Tools**

- "Software has become super cheap"
- Every team can have custom AI tools
- No more generic SaaS adoption friction
- Best-in-class APIs + custom glue

**Key Insight:**

- The opportunity isn't in replacing humans
- It's in eliminating manual work so humans can focus on high-value tasks
- MCP servers are critical infrastructure for safe, scalable AI
- Custom tools beat generic SaaS in the AI era

---

## 6. Open Source vs. Commercial

### Open Source Philosophy

**Pragmatic Approach:**

- "Fine with both"
- Like to contribute to open source
- Understand that some things are best kept private
- Decision based on strategic value, not ideology

**When IP Matters:**

- "Especially when it comes to IP that is directly correlated to your success"
- If it's your competitive advantage, keep it private
- If it's infrastructure/tooling, consider open source
- Protect what makes you unique

### When to Choose Open Source vs. Proprietary

**Open Source When:**

1. **Community Value > Competitive Advantage**
   - Discogs SDK: Enables ecosystem, not core business
   - Infrastructure/tooling that others can benefit from
   - Standard protocols and integrations

2. **Network Effects Matter**
   - More users = more contributors = better product
   - Community feedback improves the tool
   - Adoption is more valuable than licensing

3. **Learning in Public**
   - Build reputation and thought leadership
   - Attract talent and opportunities
   - Demonstrate expertise

4. **Not Core IP**
   - Supporting tools, not main product
   - Infrastructure that benefits from standardization
   - Examples: Discogs SDK, potentially MCP patterns

**Keep Proprietary When:**

1. **Direct Correlation to Success**
   - Core product differentiators
   - Unique algorithms or approaches
   - Competitive moats

2. **Commercial Value**
   - Builder CMS MCP Server: Proprietary to Builder.io
   - AI GTM platform: Internal competitive advantage
   - Builder Academy: Platform that drives business

3. **Enterprise/Security Requirements**
   - Customer data and privacy
   - Enterprise-grade features
   - SLA and support obligations

### Decision Framework

**Ask These Questions:**

1. Is this our competitive advantage?
2. Does community adoption create more value than exclusivity?
3. Will open sourcing help or hurt our business?
4. Can we maintain it if it's open source?
5. Does it enable an ecosystem we want to grow?

**Examples:**

- **Discogs SDK:** Open source (enables ecosystem, not core business)
- **Builder MCP Server:** Proprietary (core product value)
- **AI GTM:** Proprietary (competitive advantage)
- **Crate.audio:** Pivoted to open source (community value > commercial)

### Building in Public vs. Stealth Mode

**Building in Public (Preferred for Personal Projects):**

**Pros:**

- Build reputation and thought leadership
- Get feedback early and often
- Attract collaborators and opportunities
- Learn from community
- Demonstrate expertise

**Cons:**

- Ideas can be copied
- Pressure to maintain and support
- Public failures are visible

**When to Build in Public:**

- Personal projects and side projects
- Open source contributions
- Thought leadership initiatives
- Community tools and infrastructure
- Learning and experimentation

**Stealth Mode (For Commercial Projects):**

**Pros:**

- Protect competitive advantage
- Control narrative and timing
- Avoid copycats
- Perfect before launch

**Cons:**

- Miss early feedback
- Harder to build community
- Risk building wrong thing

**When to Go Stealth:**

- Core commercial products
- Competitive markets
- Novel approaches that are easily copied
- Enterprise products with long sales cycles

### Current Approach

**Personal Brand: Build in Public**

- Open source side projects (Discogs SDK)
- Share learnings and best practices
- Webinars and evangelism
- Thought leadership on AI and automation

**Commercial Work: Protect IP**

- Builder.io proprietary tools (MCP Server, AI GTM)
- Internal platforms and competitive advantages
- Enterprise features and integrations

**Balance:**

- Build reputation through open source and public building
- Protect commercial value through proprietary work
- Contribute to community while maintaining competitive edge

---

_Part 3 Career Philosophy & Positioning - Completed_


---

# Part 4: Personal Context - Interview Questions

_Date: November 7, 2025_

---

## Background & Education

### Origins: Tunisia to Montreal

**Born and Raised:**

- **Birthplace:** Hammamet, Tunisia (coastal city)
- **Upbringing:** Coastal vibes, Mediterranean culture
- **Family Background:** Born and raised in a family of entrepreneurs
- **Current Location:** Montreal, Quebec (remote work)

**Education:**

- **Bachelor in Computer Science**
- College LaSalle (Montreal, Quebec)
- Sept 2016 – April 2019
- Applied Science, University of Montreal (Sept 2015 – June 2016)

**Languages:**

- **Native Fluency:** English, French, Arabic
- **Conversational:** Spanish

### Entrepreneurial Family & Early Tech Exposure

**Family Business:**

- Parents had enterprise in tech hardware and solutions
- Grew up around hardware and technology
- Early exposure to business and entrepreneurship

**Formative Tech Experiences:**

- **Age 10:** Built own desktop computer from scratch
- **Childhood:** Fixing PCs and desktops hardware
- **Early Years:** Installing operating systems
- **Hands-On Learning:** Hardware-first approach to technology

**How This Shaped Career:**

- **Founder Mindset:** Entrepreneurial DNA from family
- **Hardware to Software:** Started with hardware, evolved to software
- **Problem-Solving:** Fixing things from young age
- **Self-Taught:** Learning by doing, not just theory
- **Builder Mentality:** Making things work, not just understanding them

### Why Computer Science?

**Natural Progression:**

- Grew up fixing computers → formal CS education
- Hardware background gave deep understanding of how computers work
- Entrepreneurial family → wanted to build businesses with software
- "Software has become super cheap" philosophy rooted in hardware cost awareness

**Formative Experiences:**

- Building desktop at age 10: learned systems thinking
- Family business: understood customer needs and business value
- Hardware troubleshooting: developed debugging mindset
- Installing OSs: understood layers of abstraction

### Multilingual Advantage

**Languages as Superpower:**

- **English:** Global tech communication
- **French:** Montreal tech scene, French clients at Builder.io
- **Arabic:** Cultural perspective, Middle East/North Africa connections
- **Spanish:** Conversational, expanding reach

**Career Impact:**

- **At Builder.io:** Help French clients directly
- **International Teams:** Bridge cultures and communication styles
- **Customer Empathy:** Understand diverse perspectives
- **Global Mindset:** Think beyond North American market

**Cultural Perspectives:**

- Mediterranean/North African background
- Canadian tech culture
- Blend of entrepreneurial and engineering mindsets
- Coastal upbringing → relaxed but driven approach

### Montreal Tech Scene

**Connection to Local Community:**

- Close to the tech scene in Montreal
- Part of vibrant startup ecosystem
- Bilingual advantage (English/French) in Quebec
- Access to both North American and European markets

**Montreal Advantages:**

- Strong AI/ML community (Mila, Element AI heritage)
- Bilingual talent pool
- Lower cost of living than SF/NYC
- Quality of life (skiing, biking, culture)
- Remote-first culture post-COVID

**Remote Work Preference:**

- Currently remote at Builder.io
- Montreal as home base
- Flexibility to work with global teams
- Best of both worlds: local community + global opportunities

---

## Hobbies & Interests (Deep Dive)

From your resume: "DJ, Travel, Ski, Tennis, Biking"

### 1. DJing 🎵

**Background:**

- **Since:** High school
- **Experience:** 10+ years
- **Venues:** Clubs in Montreal (Datcha Stereo, System)
- **Underground Scene:** Organized raves in Montreal underground scene

**Music Style:**

- **Primary:** Dance music genres
- **Genres:** Electro, Techno, Electronica, Bossa Nova
- **Influences:** Latin, and Balearic influences
- **Varies by gig:** Adapts to venue and crowd

**Philosophy:**

- "I love curating a vibe and make people dance"
- "I feel like I'm the most expressive through the music I curate"
- Focus on creating experiences, not just playing tracks
- Understanding flow and energy management

**Connection to Crate.audio:**

- **Problem:** "I want to stay in touch with my music when I actually can't listen to my records"
- **Solution:** Built Crate.audio to streamline that connection
- Personal pain point → product solution
- Vinyl collection management for DJs

**How DJing Informs Engineering:**

- **Curating a vibe = Product curation:** Select right features for right audience
- **Reading the room = User empathy:** Understand what users need in the moment
- **Flow and transitions = UX design:** Smooth experiences, no jarring changes
- **Building energy = Product momentum:** Create excitement and engagement
- **Vinyl collection = Data management:** Organizing and accessing information efficiently

### 2. Travel ✈️

**Experience:**

- **Countries Visited:** 20+ countries
- **Identity:** "Avid traveler"
- **Style:** Adventure, digital nomad, cultural exploration

**Favorite Places:**

- **Mexico City:** "Amazing for digital nomad"
- **Indonesia:** "Beautiful"
- **Food:** Peruvian and Japanese cuisine

**Best Travel Experiences:**

- **Motorbike Adventures:** "When I'm on a motorbike and I can't see the horizon in front of me it feels great"
- Sense of freedom and exploration
- Open-ended journeys
- Adventure and spontaneity

**Travel Style:**

- Digital nomad-friendly destinations
- Food-focused (Peruvian, Japanese)
- Adventure and exploration
- Motorbike travel for freedom
- Cultural immersion

**How Travel Influences Work:**

- **Global perspective:** Understand diverse markets and users
- **Adaptability:** Comfortable with change and new environments
- **Remote work:** Experience working from different locations
- **Cultural empathy:** Better understanding of international clients
- **Adventure mindset:** Willing to explore uncharted territory in tech

### 3. Skiing ⛷️

**Frequency:**

- "If I'm around a ski slope I ski"
- Opportunistic skier
- Takes advantage of proximity to mountains

**Favorite Mountains/Resorts:**

- **Whistler** (British Columbia)
- **Colorado** resorts
- **Jay Peak** (Vermont)
- **Charlevoix** (Quebec)
- **Mont Tremblant** (Quebec)

**Skiing Style:**

- Experienced skier (comfortable at major resorts)
- Enjoys variety of terrain
- Mix of local Quebec mountains and destination skiing
- Takes advantage of Montreal's proximity to great skiing

**Connection to Engineering:**

- **Problem-solving:** Reading terrain, adapting to conditions
- **Risk management:** Calculated risks, not reckless
- **Flow state:** Deep focus and presence
- **Continuous improvement:** Always refining technique

### 4. Tennis 🎾

**Frequency:**

- **Summer:** 3 times a week
- **Timing:** Before work starts
- **Social:** Plays with friends

**Style:**

- Recreational with friends
- Morning routine
- Social and fitness combined
- Consistent practice

**Benefits:**

- Morning energy boost
- Social connection
- Competitive outlet
- Physical fitness

### 5. Biking 🚴

**Montreal Cycling Culture:**

- "Montreal is an amazing city to bike"
- **Primary Transportation:** "I don't own a car"
- **Bike as transport:** Fastest way to move (when not winter)
- Car-free lifestyle

**Frequency:**

- **Non-winter months:** Regular transportation
- **Summer:** 3 times a week for tennis (biking to courts)
- Daily commuting and errands

**Style:**

- Urban cycling
- Transportation-focused
- Practical and efficient
- Part of Montreal lifestyle

**Philosophy:**

- Sustainable transportation
- Urban mobility
- Efficient and practical
- Embracing local culture (Montreal is bike-friendly)

---

### How Hobbies Connect to Work

**Common Themes:**

1. **Curating Experiences:** DJing → Product design
2. **Flow and Transitions:** Music → UX design
3. **Adventure and Exploration:** Travel → Trying new tech
4. **Problem-Solving:** Skiing → Engineering challenges
5. **Efficiency:** Biking → Optimizing workflows
6. **Community:** Organizing raves → Building platforms
7. **Sustainability:** Car-free → Efficient code/systems

**Work-Life Integration:**

- Hobbies inform product thinking (Crate.audio from DJing)
- Active lifestyle supports mental clarity
- Social activities (tennis, raves) balance solo coding
- Travel experience enables remote work
- Creative outlet (DJing) complements technical work

---

## Learning & Growth

### Learning Style (Inferred from Background)

**Building to Learn:**

- Started by building desktop at age 10
- Side projects as learning vehicles (Crate.audio, Discogs SDK, MCP Server)
- "Blazing fast prototyping" approach
- Learn by doing, not just theory

**Self-Taught Foundation:**

- Hardware background was hands-on
- Entrepreneurial family → practical learning
- Formal CS education built on self-taught foundation
- Continuous learning through building

**Side Projects as Learning:**

- **Crate.audio:** Learning AI/LLM, RAG, DAG, Next.js
- **Discogs SDK:** Learning OAuth 1.0a, TypeScript SDK development
- **MCP Server:** Learning Model Context Protocol, AI safety, guardrails
- **AI GTM:** Learning Convex, workflow automation, GTM processes

**Teaching Through Building:**

- Builder Academy (teaching through platform)
- Webinars and evangelism
- Documentation and best practices
- Open source contributions (Discogs SDK)

---

## Work-Life Balance & Integration

### Work Style (Inferred)

**Remote Work:**

- Currently fully remote at Builder.io
- Montreal as home base
- Comfortable with async communication
- Global team collaboration

**Active Lifestyle:**

- **Morning:** Tennis 3x/week before work (summer)
- **Transportation:** Bike everywhere (no car)
- **Weekends:** Skiing (when near slopes), DJing, travel
- **Balance:** Physical activity supports mental clarity

**Integration Approach:**

- Hobbies inform work (DJing → Crate.audio)
- Work enables lifestyle (remote → travel)
- Creative outlet (DJing) complements technical work
- Active lifestyle (tennis, biking, skiing) balances desk work

**Recharge Strategies:**

- DJing and music curation
- Travel and exploration
- Physical activities (skiing, tennis, biking)
- Motorbike adventures

---

## Personal Values

### Builder.io Culture Champ (Q1 2025 MVP)

**Company Values:**

- **#work-smart:** Automate 90%, focus on high-value work
- **#customer-first:** CE background, deep customer empathy
- **#raise-the-bar:** High performer, continuous improvement
- **#be-kind:** Collaborative, team-focused

**How Values Show Up in Work:**

1. **#work-smart**
   - Built Builder Academy to automate onboarding (40% CE reduction)
   - MCP Server to automate content management
   - AI GTM to automate qualification and research
   - "Software has become super cheap" philosophy

2. **#customer-first**
   - Transitioned to CE to understand customer pain
   - Managed 60+ strategic accounts
   - Built tools to unblock deals (CommerceLayer for SumUp)
   - Help French clients directly

3. **#raise-the-bar**
   - Unified Demo for best practices
   - MCP Server with extensive guardrails
   - High-quality, production-ready code
   - Thought leadership and evangelism

4. **#be-kind**
   - Helped hire 3 CEs
   - Scaled team from <30 to 100+
   - Partner enablement and certification
   - Community building (raves, open source)

### What Motivates You (Inferred)

**Gets Excited About:**

- Solving real problems (personal pain → product)
- Building platforms that scale impact
- Automating manual work
- Fast prototyping and shipping
- Creating experiences (DJing → product design)

**Core Motivations:**

- **Impact:** Build tools that help others (Academy, MCP, AI GTM)
- **Autonomy:** "Don't need designer or PM"
- **Learning:** Side projects to explore new tech
- **Building:** Entrepreneurial DNA, founder mindset
- **Community:** Organizing raves, partner enablement, open source

---

## Summary: Personal Profile

### Origin Story

- **Born:** Hammamet, Tunisia (coastal city)
- **Family:** Entrepreneurs in tech hardware
- **Age 10:** Built first desktop computer
- **Journey:** Tunisia → Montreal
- **Education:** Bachelor in CS, College LaSalle

### Languages & Culture

- **Native:** English, French, Arabic
- **Conversational:** Spanish
- **Cultural Blend:** Mediterranean/North African + Canadian
- **Global Mindset:** 20+ countries visited

### Creative Outlet

- **DJ since high school** (10+ years)
- **Genres:** Electro, Techno, Electronica, Bossa Nova
- **Influences:** Latin, Balearic
- **Venues:** Datcha Stereo, System (Montreal)
- **Community:** Organized raves in Montreal underground scene

### Active Lifestyle

- **Skiing:** Whistler, Colorado, Jay Peak, Charlevoix, Mont Tremblant
- **Tennis:** 3x/week in summer, before work
- **Biking:** Primary transportation (no car), Montreal cycling culture
- **Travel:** 20+ countries, motorbike adventures, digital nomad experience

### Core Identity

- **Builder:** Entrepreneurial DNA, founder mindset
- **Autonomous:** Don't need designer or PM
- **Fast:** Blazing fast prototyping
- **Empathetic:** Customer-first, CE background
- **Creative:** DJing informs product design
- **Global:** Multilingual, well-traveled, remote-first

---

_Part 4 Personal Context - Completed_
`;
